artist:
  name: Mega Ultra Studios
  tagline: Multimedia Production
  seo_title: "Mega Ultra Studios | Multimedia Production"
  seo_description: "Mega Ultra Studios produces Music Videos, Short and Feature Length Films, and Promotional Videos for artists, performers, and small businesses."
  # contact_twitter_username:
  contact_phone: (503) 862-6964‬
  contact_email: megaultra@mail.com 

social:
  - name: Facebook
    url: https://www.facebook.com/MegaUltraPro/
  - name: Youtube
    url: https://youtube.com/megaultrastudios
  - name: IMDB
    url: https://www.imdb.com/search/title/?companies=co0469320
  - name: Roku
    url: https://channelstore.roku.com/details/253869/details/253869/mega-ultra-studios
  - name: Amazon
    url: https://www.amazon.com/gp/video/detail/0U8DDEX8U7JZFUEYUQQ5SGPKY4/ref=imdbref_tt_wbr_pvs_piv?tag=imdbtag_tt_wbr_pvs_piv-20

site_language: en
